feat: deploy on sepolia
namehash/namekit-contracts pull request #2
Opened 2024-04-27 16:12 UTC by alextnetto

- Deployed new treasury
- updated ENS contract addresses on Sepolia in `constant.ts`
- updated hardhat configs 
- Deployed Namekit contract on Sepolia
- updated README

2024-04-28 15:47 UTC, lightwalker-eth requested changes
@alextnetto Hey thanks for the updates. Reviewed and shared feedback :+1:

2024-04-28 15:47 UTC, lightwalker-eth commented on README.md
> +   - sepolia
```suggestion
   - Sepolia
```

2024-04-28 15:47 UTC, lightwalker-eth commented on README.md
> +- Change CHAIN_ID in `.env` to the desired network you want to interact with. 1 = Mainnet, 11155111 = sepolia.
```suggestion
- Change CHAIN_ID in `.env` to the desired network you want to interact with. 1 = Mainnet, 11155111 = Sepolia.
```

2024-04-28 15:47 UTC, lightwalker-eth commented on package.json
> +    "deploy:test": "npx hardhat run script/deploy/deploy.ts --network sepolia",
```suggestion
    "deploy:sepolia": "npx hardhat run script/deploy/deploy.ts --network sepolia",
```

2024-04-28 15:47 UTC, lightwalker-eth commented on README.md
>     yarn deploy:test
```suggestion
   yarn deploy:sepolia
```

What do you think about updating this to be more specific about the testnet? Would prefer to see a specific reference to sepolia here.

2024-04-30 14:21 UTC, alextnetto reviewed
- Deployed new treasury
- updated ENS contract addresses on Sepolia in constant.ts
- updated hardhat configs
- Deployed Namekit contract on Sepolia
- updated README

2024-04-30 19:32 UTC, lightwalker-eth approved these changes
@alextnetto Updates look nice. Thanks! Approved :+1:

2024-04-30 19:32 UTC, merged